### ISSUE TITLE
Hashes instead of commits count

### ISSUE THREAD

**Issue by wwarlock** [moleksyuk/vcs-semantic-version#5]
If we have many developers with many branches (or just many branches), then sometimes it is hard to detect which build is exactly makes the problem.
Could you add the option to generate the hashes (if VCS supports this), not the numbers?

The command for git

``` bash
$ git rev-list HEAD -1
e03e23107dc98f8792ef0bbde0270c7875a251b6
```

Or the shortest hash

``` bash
$ git rev-list HEAD --abbrev-commit -1
e03e231
```

**Comment by moleksyuk** [comment]
Hi @wwarlock 

Thanks for suggestion but not sure when I'll be able to add this feature.

Here is analog plugin that supports hashes - https://github.com/cinnober/semver-git

Thanks.

**Comment by wwarlock** [comment]
Ok, thanks for your quick answer
