### ISSUE TITLE
How to configure root project to apply plugin to all projects ?

### ISSUE THREAD

**Issue by maitredede** [moleksyuk/vcs-semantic-version#6]
Hi,
I am trying to configure your plugin for a root/sub projects configuration.
I have a root empty project, and I want to apply version on all sub projects, but it seams that I have missed something. I tried different writings of my build.gradle, but either your plugin complains about missing major/minor, or when publishing with maven, I have no version at all, or your plugin does not find which vcs it is (seams that it checks the current project, not the root)

What would be a full sample of a working root/sub projects, with maven publish version set with almost everything set in root project (publish, version), only dependencies in sub projects...

Thanks.

**Comment by moleksyuk** [comment]
Hi @MaitreDede,
Unfortunately, this plugin does not support modules and I don't support it anymore. Try to find another plugin or just specify version calculation as

```
version = "1.0." + "git rev-list HEAD --count".execute().text
```

This will calculate your version on a fly.

**Comment by maitredede** [comment]
Thanks :)
